In [1]:
import gffpandas.gffpandas as gffpd
import pandas as pd
import numpy as np
from Bio import Entrez, SeqIO 
from urllib.request import urlopen
from io import StringIO
import re
from intervaltree import Interval, IntervalTree

In [2]:
from Bio import Entrez, SeqIO

In [3]:
ctrl_ph7 = gffpd.read_gff3('../sample1_modification.gff') #Wild Type pH 7
arss_ph7 = gffpd.read_gff3('../sample2_modification.gff') #ArsS deletion pH 7, cannot detect pH change
#hsdm_repair_pH7 = gffpd.read_gff3('sample3_modification.gff') #hsdM deletion and repair pH 7, test if pseudogene
hsdm_ph7 = gffpd.read_gff3('../sample4_modification.gff') #hsdM deletion pH 7, cannot methylated all motifs
ctrl_ph5 = gffpd.read_gff3('../sample5_modification.gff') #wild type pH 5
arss_ph5 = gffpd.read_gff3('../sample6_modification.gff') #ArsS deletion pH 5
#hsdm_repair_ph5 = gffpd.read_gff3('sample7_modification.gff') #hsdM deletion and repair pH 5, test if pseudogene
hsdm_ph5 = gffpd.read_gff3('../sample8_modification.gff') #hsdM deletion and repair

In [4]:
ctrl_ph7 = ctrl_ph7.attributes_to_columns()
ctrl_ph5 = ctrl_ph5.attributes_to_columns()

arss_ph7 = arss_ph7.attributes_to_columns()
arss_ph5 = arss_ph5.attributes_to_columns()

hsdm_ph7 = hsdm_ph7.attributes_to_columns()
hsdm_ph5 = hsdm_ph5.attributes_to_columns()

In [5]:
Entrez.email = "skpatterson@wm.edu"

handle = Entrez.efetch(db="nucleotide", id="CP003904.1", rettype="fasta", retmode="text")
fasta_string = handle.read()
handle.close()

In [6]:
print(fasta_string[0:100])

>CP003904.1 Helicobacter pylori 26695, complete genome
TGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGA

In [7]:
# alternate sequencing option for CP003904 fasta
Entrez.email = "skpatterson@wm.edu"

handle = Entrez.efetch(db="nucleotide", id="NC_018939.1", rettype="fasta", retmode="text")
fasta_string = handle.read()
handle.close()

In [8]:
fasta_io = StringIO(fasta_string)
record = SeqIO.read(fasta_io, "fasta")
sequence = str(record.seq)

In [9]:
sequence[3]

'T'

# CGANNNNNNTC Motif Indexing

In [20]:
def find_motifs(sequence): # for 
    pattern = 'CGA......TC'  #equivalent to CGANNNNNNTC
    results = []

    for match in re.finditer(pattern, sequence):
        start = match.start()
        end = match.end()
        actual_motif = sequence[start:end]
        results.append({
            'Start': start,
            'End': end,
            'Motif': actual_motif
        })

    return pd.DataFrame(results)

# Assuming you've already fetched and stored your sequence as a string variable 'sequence'
cga = find_motifs(sequence)

In [21]:
cga.head()

   Start    End        Motif
0   3680   3691  CGAAATGTATC
1   5752   5763  CGATCCCATTC
2   8759   8770  CGATGAGTTTC
3  10440  10451  CGATAACGATC
4  17458  17469  CGAAGCTTATC

In [22]:
ctrl_ph7[ctrl_ph7['start'] <= 1714]

,seq_id,source,type,start,end,score,strand,phase,attributes,IPDRatio,context,coverage,id,identificationQv,motif
2,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,255,255,713,+,.,context=AGTGAGCTTTTTGCTCAAAGAATCCAAGATAGCGTTTA...,5.35,AGTGAGCTTTTTGCTCAAAGAATCCAAGATAGCGTTTAAAA,534,GANTC,656,GANTC
5,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,279,279,53,+,.,coverage=552;context=CAAGATAGCGTTTAAAAATTTAGGG...,1.55,CAAGATAGCGTTTAAAAATTTAGGGGTGTTAGGCTCAGCGT,552,None,None,None
6,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,300,300,740,+,.,context=AGGGGTGTTAGGCTCAGCGTAGAGTTTGCCAAGCTCTA...,5.36,AGGGGTGTTAGGCTCAGCGTAGAGTTTGCCAAGCTCTATGC,545,RCGDAD,695,RCGDAD
7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,309,309,116,+,.,coverage=550;context=AGGCTCAGCGTAGAGTTTGCCAAGC...,1.94,AGGCTCAGCGTAGAGTTTGCCAAGCTCTATGCATTCATTGA,550,None,100,None
8,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,331,331,35,+,.,coverage=554;context=AGCTCTATGCATTCATTGATGATGA...,1.41,AGCTCTATGCATTCATTGATGATGATAGGGTTTTGCGTGGG,554,None,None,None
9,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,341,341,31,+,.,coverage=488;context=ATTCATTGATGATGATAGGGTTTTG...,1.36,ATTCATTGATGATGATAGGGTTTTGCGTGGGCGTGAAGCCA,488,None,None,None
10,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,352,352,41,+,.,coverage=547;context=ATGATAGGGTTTTGCGTGGGCGTGA...,1.51,ATGATAGGGTTTTGCGTGGGCGTGAAGCCAATTTCATACGC,547,None,14,None
11,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,361,361,26,+,.,coverage=538;context=TTTTGCGTGGGCGTGAAGCCAATTT...,1.36,TTTTGCGTGGGCGTGAAGCCAATTTCATACGCTCCTAAGCG,538,None,8,None
13,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,383,383,526,+,.,context=TTTCATACGCTCCTAAGCGTAAAATCGCCTTTTCCATG...,4.56,TTTCATACGCTCCTAAGCGTAAAATCGCCTTTTCCATGCTC,525,RCGDAD,494,RCGDAD
15,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,398,398,694,+,.,context=AGCGTAAAATCGCCTTTTCCATGCTCCCTAATCGCTTG...,4.80,AGCGTAAAATCGCCTTTTCCATGCTCCCTAATCGCTTGAAA,549,CATG,659,CATG
18,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,412,412,50,+,.,coverage=547;context=TTTTCCATGCTCCCTAATCGCTTGA...,1.51,TTTTCCATGCTCCCTAATCGCTTGAAATCCCAGTCTTTTAA,547,None,None,None
19,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,422,422,80,+,.,coverage=555;context=TCCCTAATCGCTTGAAATCCCAGTC...,1.73,TCCCTAATCGCTTGAAATCCCAGTCTTTTAAATGCGGCTCG,555,None,44,None
22,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,443,443,727,+,.,context=AGTCTTTTAAATGCGGCTCGATGAGGGCGTCAATTTCA...,5.66,AGTCTTTTAAATGCGGCTCGATGAGGGCGTCAATTTCATTG,547,TCGA,746,TCGA
23,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,446,446,444,+,.,context=CTTTTAAATGCGGCTCGATGAGGGCGTCAATTTCATTG...,3.59,CTTTTAAATGCGGCTCGATGAGGGCGTCAATTTCATTGATT,551,GAGG,427,GAGG
28,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,531,531,618,+,.,context=GTTGTTTTTAATCTTTTTTTCTTCTAACATGCTAGAAG...,4.71,GTTGTTTTTAATCTTTTTTTCTTCTAACATGCTAGAAGCGA,548,GAAGA/TCTTC,605,TCTTC
29,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,539,539,751,+,.,context=TAATCTTTTTTTCTTCTAACATGCTAGAAGCGATTTTT...,5.48,TAATCTTTTTTTCTTCTAACATGCTAGAAGCGATTTTTTTA,561,CATG,699,CATG
32,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,564,564,274,+,.,context=AGAAGCGATTTTTTTAATTTCTTCATTACCGCTCTCAA...,2.60,AGAAGCGATTTTTTTAATTTCTTCATTACCGCTCTCAAACG,550,GAAGA/TCTTC,231,TCTTC
33,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,671,671,39,+,.,context=TGGCACAAGCTCAACAATTCAATGAGGGTGCTCATCGC...,1.54,TGGCACAAGCTCAACAATTCAATGAGGGTGCTCATCGCTTC,566,HHTCAVNNNNNNTGY,45,HHTCAVNNNNNNTGY
34,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,675,675,504,+,.,context=ACAAGCTCAACAATTCAATGAGGGTGCTCATCGCTTCA...,3.88,ACAAGCTCAACAATTCAATGAGGGTGCTCATCGCTTCAAAG,569,GAGG,535,GAGG
38,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,777,777,695,+,.,context=GCACGCCAAAGCTTACCGGCATGCTGTATTTAAGCATC...,4.52,GCACGCCAAAGCTTACCGGCATGCTGTATTTAAGCATCGCA,575,CATG,674,CATG
40,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,797,797,641,+,.,context=ATGCTGTATTTAAGCATCGCATGGGCAATACCCTTAGT...,4.50,ATGCTGTATTTAAGCATCGCATGGGCAATACCCTTAGTCGC,576,CATG,629,CATG
43,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,845,845,559,+,.,context=CTCACATAATCAAAATGCGGAGTCCCCCCTCTAATGAT...,4.19,CTCACATAATCAAAATGCGGAGTCCCCCCTCTAATGATCGC,564,"RCGDAD,GANTC",664,"RCGDAD,GANTC"
45,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,851,851,54,+,.,coverage=561;context=TAATCAAAATGCGGAGTCCCCCCTC...,1.52,TAATCAAAATGCGGAGTCCCCCCTCTAATGATCGCTCCCAA,561,None,34,None
47,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,861,861,811,+,.,context=GCGGAGTCCCCCCTCTAATGATCGCTCCCAAAACGCAC...,5.38,GCGGAGTCCCCCCTCTAATGATCGCTCCCAAAACGCACACG,557,GATC,820,GATC
49,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,896,896,46,+,.,coverage=556;context=CACACGCCATCGTATTTTTCGCTCT...,1.49,CACACGCCATCGTATTTTTCGCTCTCTAATAATTTGTCTAA,556,None,None,None
51,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,965,965,1013,+,.,context=ACCAGCACGATGTCTAAAAGATCCTCATCGCCCCCATG...,8.02,ACCAGCACGATGTCTAAAAGATCCTCATCGCCCCCATGCCT,548,GATC,991,GATC
54,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,980,980,663,+,.,context=AAAAGATCCTCATCGCCCCCATGCCTTTTAAAGCAGTC...,4.68,AAAAGATCCTCATCGCCCCCATGCCTTTTAAAGCAGTCCAT,549,CATG,632,CATG
56,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,994,994,665,+,.,context=GCCCCCATGCCTTTTAAAGCAGTCCATCGCCCCTTCTT...,4.98,GCCCCCATGCCTTTTAAAGCAGTCCATCGCCCCTTCTTGCA,541,GCAG,636,GCAG
58,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,1005,1005,38,+,.,coverage=548;context=TTTTAAAGCAGTCCATCGCCCCTTC...,1.45,TTTTAAAGCAGTCCATCGCCCCTTCTTGCAATCTGTCTGTG,548,None,40,None
60,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,1041,1041,36,+,.,coverage=532;context=CTGTGATGATATGATTGAAGCGCGA...,1.41,CTGTGATGATATGATTGAAGCGCGATGTTAAAATAGCGACT,532,None,None,None
61,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1059,1059,446,+,.,context=AGCGCGATGTTAAAATAGCGACTCTTTCATTCCCTTGT...,3.49,AGCGCGATGTTAAAATAGCGACTCTTTCATTCCCTTGTAAT,551,GANTC,419,GANTC
63,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,1088,1088,120,+,.,coverage=520;context=TTCCCTTGTAATTGCAATTTCCCTT...,1.94,TTCCCTTGTAATTGCAATTTCCCTTCTATGATTTGCATGAA,520,None,58,None
64,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,1089,1089,278,+,.,coverage=563;context=TCCCTTGTAATTGCAATTTCCCTTC...,2.85,TCCCTTGTAATTGCAATTTCCCTTCTATGATTTGCATGAAA,563,None,168,None
66,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1104,1104,685,+,.,context=ATTTCCCTTCTATGATTTGCATGAAATTCCTTTAAAAT...,4.89,ATTTCCCTTCTATGATTTGCATGAAATTCCTTTAAAATAAA,565,CATG,656,CATG
68,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1140,1140,676,+,.,context=ATAAATTTTGGATTTTTAACATGTCGGTTACTAATTGT...,5.45,ATAAATTTTGGATTTTTAACATGTCGGTTACTAATTGTTCT,561,CATG,679,CATG
70,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1179,1179,596,+,.,context=CTAGCTCGTCAGGTTTTAGCATGTTTGCTCCATCGCTT...,4.68,CTAGCTCGTCAGGTTTTAGCATGTTTGCTCCATCGCTTAGG,563,CATG,566,CATG
72,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1211,1211,497,+,.,context=TCGCTTAGGGCGTTTTTAGGATCAACATGCGTTTCAGC...,3.87,TCGCTTAGGGCGTTTTTAGGATCAACATGCGTTTCAGCAAA,564,GATC,721,GATC
74,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1217,1217,746,+,.,context=AGGGCGTTTTTAGGATCAACATGCGTTTCAGCAAACAA...,5.60,AGGGCGTTTTTAGGATCAACATGCGTTTCAGCAAACAACCC,563,CATG,716,CATG
76,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1259,1259,910,+,.,context=TCAATCCCCACCGCCGCCGCAGCTCTCGCTAAAATAGG...,7.74,TCAATCCCCACCGCCGCCGCAGCTCTCGCTAAAATAGGGGC,563,GCAG,844,GCAG
79,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,1342,1342,36,+,.,coverage=559;context=CATTTGCACGCTATGGGTAGCGTCA...,1.42,CATTTGCACGCTATGGGTAGCGTCAAAAATCACAGGGGCAA,559,None,None,None
80,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1371,1371,708,+,.,context=TCACAGGGGCAAATTCTCGCATGATTTTTAAAGAGCGC...,5.88,TCACAGGGGCAAATTCTCGCATGATTTTTAAAGAGCGCATA,568,CATG,670,CATG
85,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,1438,1438,37,+,.,coverage=555;context=GCTGCTCCCCCTTTCACACAGCCAC...,1.42,GCTGCTCCCCCTTTCACACAGCCACACGCCATTTTTTAACG,555,None,None,None
88,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1527,1527,602,+,.,context=CCTTTAGAACAGAATATTGCATGTCTTTTGGGTTCATG...,4.32,CCTTTAGAACAGAATATTGCATGTCTTTTGGGTTCATGAAT,563,CATG,564,CATG
90,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1542,1542,669,+,.,context=ATTGCATGTCTTTTGGGTTCATGAATTGCCCTTTTTTG...,5.60,ATTGCATGTCTTTTGGGTTCATGAATTGCCCTTTTTTGATA,556,CATG,655,CATG
92,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1601,1601,702,+,.,context=TGGCTCACTTCTACAATCAGATCCGTTTGGCGGCACAA...,4.46,TGGCTCACTTCTACAATCAGATCCGTTTGGCGGCACAAAAA,564,GATC,660,GATC
94,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,1625,1625,30,+,.,coverage=559;context=GTTTGGCGGCACAAAAACGCCGGGA...,1.41,GTTTGGCGGCACAAAAACGCCGGGATTTGTAAAATATCCGC,559,None,5,None
98,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,1679,1679,625,+,.,context=ACGCTTGCTTGATAACTCTCATGCACATCGGTTAAGAT...,4.30,ACGCTTGCTTGATAACTCTCATGCACATCGGTTAAGATTTT,553,CATG,602,CATG
100,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,1711,1711,71,+,.,coverage=516;context=TAAGATTTTATAACCAAATTCCTCT...,1.66,TAAGATTTTATAACCAAATTCCTCTTTGATCGTTTGTAACA,516,None,52,None

In [23]:
# go -1 from start methyl mark, and fastq only have + end, so - end motifs aren't marked in dataframe
# for example 255 is a m6A found in ctrl_ph7 with motif GANTC
sequence[250:259]

'AAAGAATCC'

In [24]:
# next thing to do is index everywhere with a + strand 
ctrl_ph7 = ctrl_ph7[ctrl_ph7['strand'] == '+']
ctrl_ph5 = ctrl_ph5[ctrl_ph5['strand'] == '+']

arss_ph7 = arss_ph7[arss_ph7['strand'] == '+']
arss_ph5 = arss_ph5[arss_ph5['strand'] == '+']

hsdm_ph7 = hsdm_ph7[hsdm_ph7['strand'] == '+']
hsdm_ph5 = hsdm_ph5[hsdm_ph5['strand'] == '+']

In [25]:
print(f"\nTotal motifs found: {len(cga)}")

Total motifs found: 609

In [15]:
#now, we're going to compare the start colum of ctrl_ph7 to cga

In [16]:
!pip install intervaltree

Requirement already satisfied: intervaltree in /Users/sarahpatterson/miniconda3/lib/python3.12/site-packages (3.1.0)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /Users/sarahpatterson/miniconda3/lib/python3.12/site-packages (from intervaltree) (2.4.0)

In [26]:
tree = IntervalTree(Interval(start, start + 1) for start in ctrl_ph7['start'])

def is_methylated(start, end, tree):
    return any(tree[start:end + 1])

cga['methylated in ctrl_ph7'] = cga.apply(lambda row: is_methylated(row['Start'], row['End'], tree), axis=1)

cga

       Start      End        Motif  methylated in ctrl_ph7
0       3680     3691  CGAAATGTATC                   False
1       5752     5763  CGATCCCATTC                    True
2       8759     8770  CGATGAGTTTC                   False
3      10440    10451  CGATAACGATC                    True
4      17458    17469  CGAAGCTTATC                    True
..       ...      ...          ...                     ...
604  1650155  1650166  CGATTTTCTTC                    True
605  1650374  1650385  CGATTGTCCTC                   False
606  1656882  1656893  CGAGCATTATC                   False
607  1664006  1664017  CGAGGGCTATC                    True
608  1666289  1666300  CGACCGCATTC                   False

[609 rows x 4 columns]

In [27]:
cga

       Start      End        Motif  methylated in ctrl_ph7
0       3680     3691  CGAAATGTATC                   False
1       5752     5763  CGATCCCATTC                    True
2       8759     8770  CGATGAGTTTC                   False
3      10440    10451  CGATAACGATC                    True
4      17458    17469  CGAAGCTTATC                    True
..       ...      ...          ...                     ...
604  1650155  1650166  CGATTTTCTTC                    True
605  1650374  1650385  CGATTGTCCTC                   False
606  1656882  1656893  CGAGCATTATC                   False
607  1664006  1664017  CGAGGGCTATC                    True
608  1666289  1666300  CGACCGCATTC                   False

[609 rows x 4 columns]

In [14]:
def create_interval_tree(df):
    return IntervalTree(Interval(start, start + 1) for start in df['start'])

def is_methylated(start, end, tree):
    return any(tree[start:end + 1])

tree_ctrl_ph7 = create_interval_tree(ctrl_ph7)
tree_ctrl_ph5 = create_interval_tree(ctrl_ph5)
tree_hsdm_ph7 = create_interval_tree(hsdm_ph7)
tree_hsdm_ph5 = create_interval_tree(hsdm_ph5)

cga['methylated in ctrl_ph7'] = cga.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph7), axis=1)
cga['methylated in ctrl_ph5'] = cga.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph5), axis=1)
cga['methylated in hsdm_ph7'] = cga.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph7), axis=1)
cga['methylated in hsdm_ph5'] = cga.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph5), axis=1)

cga

,Start,End,Motif,methylated in ctrl_ph7,methylated in ctrl_ph5,methylated in hsdm_ph7,methylated in hsdm_ph5
0,3680,3691,CGAAATGTATC,False,False,False,False
1,5752,5763,CGATCCCATTC,True,True,True,True
2,8759,8770,CGATGAGTTTC,False,False,False,False
3,10440,10451,CGATAACGATC,True,True,True,True
4,17458,17469,CGAAGCTTATC,True,False,False,True
...,...,...,...,...,...,...,...
604,1650155,1650166,CGATTTTCTTC,True,True,True,True
605,1650374,1650385,CGATTGTCCTC,False,False,False,False
606,1656882,1656893,CGAGCATTATC,False,False,False,False
607,1664006,1664017,CGAGGGCTATC,True,True,True,True
608,1666289,1666300,CGACCGCATTC,False,False,False,False

# CCANNNNNNTC

In [16]:
def find_motifs(sequence): # for CCANNNNNNTC
    pattern = 'CGRAT'  #equivalent to CCANNNNNNTC
    results = []

    for match in re.finditer(pattern, sequence):
        start = match.start()
        end = match.end()
        actual_motif = sequence[start:end]
        results.append({
            'Start': start,
            'End': end,
            'Motif': actual_motif
        })

    return pd.DataFrame(results)

# Assuming you've already fetched and stored your sequence as a string variable 'sequence'
cca = find_motifs(sequence)

In [17]:
def create_interval_tree(df):
    return IntervalTree(Interval(start, start + 1) for start in df['start'])

def is_methylated(start, end, tree):
    return any(tree[start:end + 1])

tree_ctrl_ph7 = create_interval_tree(ctrl_ph7)
tree_ctrl_ph5 = create_interval_tree(ctrl_ph5)
tree_hsdm_ph7 = create_interval_tree(hsdm_ph7)
tree_hsdm_ph5 = create_interval_tree(hsdm_ph5)

cca['methylated in ctrl_ph7'] = cca.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph7), axis=1)
cca['methylated in ctrl_ph5'] = cca.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph5), axis=1)
cca['methylated in hsdm_ph7'] = cca.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph7), axis=1)
cca['methylated in hsdm_ph5'] = cca.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph5), axis=1)

cca[1:100]

ValueError: Cannot set a DataFrame without columns to the column methylated in ctrl_ph7

## well, how can i not do rcgdad...
### this can be applied now to any motif with degenerate bases!

In [17]:
def find_motifs(sequence, motif):
    degenerate_bases = {
        'R': '[AG]',
        'Y': '[CT]',
        'S': '[GC]',
        'W': '[AT]',
        'K': '[GT]',
        'M': '[AC]',
        'B': '[CGT]',
        'D': '[AGT]',
        'H': '[ACT]',
        'V': '[ACG]',
        'N': '[ATCG]',
        'A': 'A',
        'C': 'C',
        'G': 'G',
        'T': 'T'
    }

    # Convert the motif into a regular expression pattern
    pattern = ''.join(degenerate_bases[base] for base in motif)
    results = []

    for match in re.finditer(pattern, sequence):
        start = match.start()
        end = match.end()
        actual_motif = sequence[start:end]
        results.append({
            'Start': start,
            'End': end,
            'Motif': actual_motif
        })

    return pd.DataFrame(results)

def create_interval_tree(df):
    return IntervalTree(Interval(start, start + 1) for start in df['start'])

def is_methylated(start, end, tree):
    return any(tree[start:end + 1])


tree_ctrl_ph7 = create_interval_tree(ctrl_ph7)
tree_ctrl_ph5 = create_interval_tree(ctrl_ph5)
tree_hsdm_ph7 = create_interval_tree(hsdm_ph7)
tree_hsdm_ph5 = create_interval_tree(hsdm_ph5)

In [18]:
motif = "CGRAT"
rcgdad = find_motifs(sequence, motif)
rcgdad

        Start      End  Motif
0        1911     1916  CGGAT
1        5849     5854  CGAAT
2        7984     7989  CGAAT
3       10361    10366  CGAAT
4       10901    10906  CGGAT
...       ...      ...    ...
1654  1661716  1661721  CGGAT
1655  1663031  1663036  CGAAT
1656  1663729  1663734  CGGAT
1657  1664230  1664235  CGGAT
1658  1664305  1664310  CGGAT

[1659 rows x 3 columns]

In [19]:
rcgdad['methylated in ctrl_ph7'] = rcgdad.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph7), axis=1)
rcgdad['methylated in ctrl_ph5'] = rcgdad.apply(lambda row: is_methylated(row['Start'], row['End'], tree_ctrl_ph5), axis=1)
rcgdad['methylated in hsdm_ph7'] = rcgdad.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph7), axis=1)
rcgdad['methylated in hsdm_ph5'] = rcgdad.apply(lambda row: is_methylated(row['Start'], row['End'], tree_hsdm_ph5), axis=1)

rcgdad

,Start,End,Motif,methylated in ctrl_ph7,methylated in ctrl_ph5,methylated in hsdm_ph7,methylated in hsdm_ph5
0,1911,1916,CGGAT,True,True,True,True
1,5849,5854,CGAAT,True,True,True,True
2,7984,7989,CGAAT,True,True,True,True
3,10361,10366,CGAAT,True,True,True,True
4,10901,10906,CGGAT,True,True,True,True
...,...,...,...,...,...,...,...
1654,1661716,1661721,CGGAT,True,True,True,True
1655,1663031,1663036,CGAAT,True,True,True,True
1656,1663729,1663734,CGGAT,True,True,True,True
1657,1664230,1664235,CGGAT,True,True,True,True
1658,1664305,1664310,CGGAT,True,True,True,True

In [21]:
rcgdad[rcgdad['methylated in ctrl_ph5'] == False]

,Start,End,Motif,methylated in ctrl_ph7,methylated in ctrl_ph5,methylated in hsdm_ph7,methylated in hsdm_ph5
91,1555716,1555724,GCGCGCAT,True,False,True,False

In [26]:
rcgdad[rcgdad['methylated in ctrl_ph7'] == False]

,Start,End,Motif,methylated in ctrl_ph7,methylated in ctrl_ph5,methylated in hsdm_ph7,methylated in hsdm_ph5
217,1013883,1013889,CCGGAT,False,False,False,False

In [27]:
rcgdad[rcgdad['methylated in hsdm_ph7'] == False]

,Start,End,Motif,methylated in ctrl_ph7,methylated in ctrl_ph5,methylated in hsdm_ph7,methylated in hsdm_ph5
217,1013883,1013889,CCGGAT,False,False,False,False