In [1]:
import gffpandas.gffpandas as gffpd
import pandas as pd
import numpy as np

In [9]:
#all dataframes from previous working steps
merged = pd.read_csv("methylation_df.csv")
ctrl_unique = pd.read_csv('./methyl_point_diff/ctrl_diff_all.csv')
ars_unique = pd.read_csv('./methyl_point_diff/arsS_diff_all.csv')
ph5_unique = pd.read_csv('./methyl_point_diff/pH5_diff_all.csv')
ph7_unique = pd.read_csv('./methyl_point_diff/pH7_diff_all.csv')

# annotated dataframes
annot = pd.read_csv("../hpy_annot.tsv",sep='\t')#hpy annotation file
annot = annot.drop(columns=["seqname", "source", "feature", "score", "frame", "Prot_Size(est)", "attribute"]) #clean
tss = pd.read_csv("../TSS.csv")

In [6]:
ctrl_unique.head()

,Unnamed: 0,sample,seq_id,source,type,start,end,score,strand,phase,...,context,coverage,id,identificationQv,motif,Classification,promoter_ID,CodingRegion_ID,CodingRegion_gene_type,Promoter_gene_type
0,107,ctrl pH7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,2946,2946,122,+,.,...,GCAAATGCCGCACTAGAATGCGCGAAATTAGACATTGACAT,544,NaN,59.0,NaN,Coding Region,NaN,HP0005,"PURINES, PYRIMIDINES, NUCLEOSIDES AND NUCLEOTIDES",NaN
1,191,ctrl pH7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,modified_base,5835,5835,127,+,.,...,TTATGCCCTAATTCTTGCGTGGCGCTTAATAATTGCGAATA,521,NaN,NaN,NaN,Coding Region,NaN,HP0009,CELL ENVELOPE,NaN
2,195,ctrl pH7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,6033,6033,108,+,.,...,CTAAAATCAAGTATCGTGCGCGCCAACAACTCAGATTGCTT,526,NaN,26.0,NaN,Coding Region,NaN,HP0009,CELL ENVELOPE,NaN
3,237,ctrl pH7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,7151,7151,123,+,.,...,GGTGTTTTTCACCATTTGAGCGGCTTCACCGATTTGATAGC,511,NaN,66.0,NaN,Intergenic Region,NaN,NaN,NaN,NaN
4,258,ctrl pH7,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m4C,7831,7831,127,+,.,...,CTAGCGTTAAAACCAAAATGCCCTTCGTGTTTTTCTACTTC,469,NaN,102.0,NaN,Coding Region,NaN,HP0010,CELLULAR PROCESSES,NaN

In [10]:
counts = pd.DataFrame(columns=['gene', 'ctrl differences','arsS differences', 'pH 5 differences', 'pH 7 differences'])
counts['gene'] = annot['HP_number']
counts.head()

     gene ctrl differences arsS differences pH 5 differences pH 7 differences
0  HP0001              NaN              NaN              NaN              NaN
1  HP0002              NaN              NaN              NaN              NaN
2  HP0003              NaN              NaN              NaN              NaN
3  HP0004              NaN              NaN              NaN              NaN
4  HP0005              NaN              NaN              NaN              NaN

In [11]:
for ind in counts.index: 
    counts.loc[ind, 'ctrl differences']=((ctrl_unique['start'].between(annot.loc[ind,'start'], annot.loc[ind,'end']+1))).sum()
    counts.loc[ind, 'arsS differences']=((ars_unique['start'].between(annot.loc[ind,'start'], annot.loc[ind,'end']+1))).sum()
    counts.loc[ind, 'pH 5 differences']=((ph5_unique['start'].between(annot.loc[ind,'start'], annot.loc[ind,'end']+1))).sum()
    counts.loc[ind, 'pH 7 differences']=((ph7_unique['start'].between(annot.loc[ind,'start'], annot.loc[ind,'end']+1))).sum()

In [12]:
counts

,gene,ctrl differences,arsS differences,pH 5 differences,pH 7 differences
0,HP0001,0,0,0,0
1,HP0002,1,0,2,1
2,HP0003,0,0,0,0
3,HP0004,0,1,3,2
4,HP0005,3,1,0,2
...,...,...,...,...,...
1585,HP1586,0,0,0,0
1586,HP1587,0,0,0,0
1587,HP1588,0,0,0,0
1588,HP1589,2,0,1,1
1589,HP1590,1,0,0,1

In [16]:
ph5_unique[ph5_unique['start'] <= 1105]

,Unnamed: 0,sample,seq_id,source,type,start,end,score,strand,phase,...,context,coverage,id,identificationQv,motif,Classification,promoter_ID,CodingRegion_ID,CodingRegion_gene_type,Promoter_gene_type
0,59697,ctrl pH5,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,679,679,197,-,.,...,AGGGCTTTGAAGCGATGAGCACCCTCATTGAATTGTTGAGC,479,NaN,178.0,NaN,Coding Region,NaN,HP0002,"BIOSYNTHESIS OF COFACTORS, PROSTHETIC GROUPS, ...",NaN
1,59714,ctrl pH5,CP003904_1_Helicobacter_pylori26695_complete_g...,kinModCall,m6A,996,996,93,-,.,...,ATTGCAAGAAGGGGCGATGGACTGCTTTAAAAGGCATGGGG,460,NaN,66.0,NaN,Coding Region,NaN,HP0002,"BIOSYNTHESIS OF COFACTORS, PROSTHETIC GROUPS, ...",NaN